platform :ios, '15.0'

target 'kfit' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseAppCheckInterop'
  pod 'GoogleSignIn'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'FIREBASE_CORE_VERSION=@"10.15.0"',
        ]
      end
    end
  end
end

target 'kfitWatch' do
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end

target 'kfitWatchKit Extension' do
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end
